Merge Data that scraped from scraper 1 (marcus/vs)

In [1]:
import pandas as pd
import os 
from tqdm import tqdm

In [3]:
print (os.getcwd())

c:\Users\yugik\OneDrive - Singapore Institute Of Technology\Y2 T2\INF2008 MACHINE LEARNING\Project\ProjectTesting\ScappingMaterials

In [12]:
directory = os.path.join(os.getcwd(), 'MarcusVS','ScrappedData')
directory 
finalDF = pd.DataFrame() 
for folder in os.listdir(directory):
    print(folder)
    #check if its a folder 
    if not os.path.isdir(os.path.join(directory, folder)):
        continue 
    for file in os.listdir(os.path.join(directory, folder)):
        print(file)
        df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip') 
        finalDF = pd.concat([finalDF, df], ignore_index=True)

3u-csc
3u-csc_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

5j-ceb
5j-ceb_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

6e-igo
6e-igo_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

7c-jja
7c-jja_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

8b-tnu
8b-tnu_aircraft_data.csv
8g-dtl
8g-dtl_aircraft_data.csv
8m-mma
8m-mma_aircraft_data.csv
9c-cqh
9c-cqh_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ac-aca
ac-aca_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

af-afr
af-afr_aircraft_data.csv
ai-aic
ai-aic_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ak-axm
ak-axm_aircraft_data.csv
ay-fin
ay-fin_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ba-baw
ba-baw_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

bg-bbc
bg-bbc_aircraft_data.csv
bi-rba
bi-rba_aircraft_data.csv
br-eva
br-eva_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ca-cca
ca-cca_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ci-cal
ci-cal_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

cx-cpa
cx-cpa_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

cz-csn
cz-csn_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ek-uae
ek-uae_aircraft_data.csv
et-eth
et-eth_aircraft_data.csv
ey-etd
ey-etd_aircraft_data.csv
fj-fji
fj-fji_aircraft_data.csv
fy-ffm
fy-ffm_aircraft_data.csv
ga-gia
ga-gia_aircraft_data.csv
gf-gfa
gf-gfa_aircraft_data.csv
gj-cdc
gj-cdc_aircraft_data.csv
gs-gcr
gs-gcr_aircraft_data.csv
gx-cbg
gx-cbg_aircraft_data.csv
ho-dkh
ho-dkh_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

hu-chh
hu-chh_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

id-btk
id-btk_aircraft_data.csv
ix-axb
ix-axb_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

jl-jal
jl-jal_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

jq-jst
jq-jst_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

jx-sjx
jx-sjx_aircraft_data.csv
ke-kal
ke-kal_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

kl-klm
kl-klm_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

kr-kme
kr-kme_aircraft_data.csv
lh-dlh
lh-dlh_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

lx-swr
lx-swr_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

mf-cxa
mf-cxa_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

mh-mas
mh-mas_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

mm-apj
mm-apj_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

mu-ces
mu-ces_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ns-hbh
ns-hbh_aircraft_data.csv
oq-cqn
oq-cqn_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

oz-aar
oz-aar_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

pg-bkp
pg-bkp_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

pn-chb
pn-chb_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

pr-pal
pr-pal_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

progress.json
px-ang
px-ang_aircraft_data.csv
qf-qfa
qf-qfa_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

qg-ctv
qg-ctv_aircraft_data.csv
qr-qtr
qr-qtr_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

sb-aci
sb-aci_aircraft_data.csv
sc-cdg
sc-cdg_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

sl-tlm
sl-tlm_aircraft_data.csv
sq-sia
sq-sia_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

sv-sva
sv-sva_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

tg-tha
tg-tha_aircraft_data.csv
tk-thy
tk-thy_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

tr-tgw
tr-tgw_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

ua-ual
ua-ual_aircraft_data.csv
ub-uba
ub-uba_aircraft_data.csv
ul-alk
ul-alk_aircraft_data.csv
vj-vjc
vj-vjc_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

vn-hvn
vn-hvn_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

zg-tzp
zg-tzp_aircraft_data.csv
zh-csz
zh-csz_aircraft_data.csv

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1449524645.py:11: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(directory, folder, file), on_bad_lines='skip')

In [13]:
finalDF

,Airline Code,Aircraft Registration,Aircraft Link,Aircraft,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11264563,zh-csz,b-225k,https://www.flightradar24.com/data/aircraft/b-...,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,29 Sep 2024,Shenzhen(SZX),Wuxi(WUX),ZH9801,2:12,07:20,07:43,09:35,Landed 09:55,yellow
11264564,zh-csz,b-225k,https://www.flightradar24.com/data/aircraft/b-...,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Chongqing(CKG),Shenzhen(SZX),ZH9426,1:41,20:25,00:01,22:40,Landed 01:42,red
11264565,zh-csz,b-225k,https://www.flightradar24.com/data/aircraft/b-...,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Chongqing(CKG),ZH9425,1:54,17:05,21:05,19:15,Landed 22:59,red
11264566,zh-csz,b-225k,https://www.flightradar24.com/data/aircraft/b-...,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Nanjing(NKG),Shenzhen(SZX),ZH8982,2:28,14:55,16:34,17:20,Landed 19:02,red
11264567,zh-csz,b-225k,https://www.flightradar24.com/data/aircraft/b-...,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Nanjing(NKG),ZH8981,1:57,11:10,11:31,13:25,Landed 13:27,green

Download the complete data retrieved through MARCUSVS script

In [14]:
finalDF.to_csv('DataMARCUSVS.csv', index=False)

Merge Data that scraped from scraper 2 (ZF)

In [15]:
directory = os.path.join(os.getcwd(), 'ZF','data')
finalDF1 = pd.DataFrame() 
for item in os.listdir(directory):
    if item.endswith('.csv'):
        print(item)
        df = pd.read_csv(os.path.join(directory, item))
        finalDF1 = pd.concat([finalDF1, df], ignore_index=True)

air-japan_nq-ajx.csv
air-macau_nx-amu.csv
air-new-zealand_nz-anz.csv
all-nippon-airways_nh-ana.csv
japan-airlines_jl-jal.csv
peach_mm-apj.csv
singapore-airlines_sq-sia.csv

Download the complete data retrieved through ZF script

In [17]:
finalDF1.to_csv('DataZF.csv', index=False)

MERGED BOTH

In [23]:
finalDF1.head()

,planeID,aircraftTypeCode,operator,code,modeS,serialNumber,age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,ONTIME,STATUS
0,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,14 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:14,12:15 AM,12:54 AM,8:10 AM,green,Landed 8:08 AM
1,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Bangkok (BKK),NQ1,6:47,5:35 PM,5:53 PM,11:00 PM,green,Landed 10:40 PM
2,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Seoul (ICN),Tokyo (NRT),NQ22,1:48,1:40 PM,1:58 PM,4:00 PM,green,Landed 3:46 PM
3,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Seoul (ICN),NQ21,2:20,9:50 AM,10:02 AM,12:30 PM,green,Landed 12:22 PM
4,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:04,12:15 AM,1:12 AM,8:10 AM,green,Landed 8:16 AM

In [24]:
finalDF.head()

,Airline Code,Aircraft Registration,Aircraft Link,Aircraft,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,https://www.flightradar24.com/data/aircraft/b-...,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green

In [27]:
finalDF.drop(["Aircraft Link"], axis=1, inplace=True)
finalDF

,Airline Code,Aircraft Registration,Aircraft,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Airbus A320-271N,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11264563,zh-csz,b-225k,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,29 Sep 2024,Shenzhen(SZX),Wuxi(WUX),ZH9801,2:12,07:20,07:43,09:35,Landed 09:55,yellow
11264564,zh-csz,b-225k,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Chongqing(CKG),Shenzhen(SZX),ZH9426,1:41,20:25,00:01,22:40,Landed 01:42,red
11264565,zh-csz,b-225k,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Chongqing(CKG),ZH9425,1:54,17:05,21:05,19:15,Landed 22:59,red
11264566,zh-csz,b-225k,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Nanjing(NKG),Shenzhen(SZX),ZH8982,2:28,14:55,16:34,17:20,Landed 19:02,red
11264567,zh-csz,b-225k,Boeing 737 MAX 8,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Nanjing(NKG),ZH8981,1:57,11:10,11:31,13:25,Landed 13:27,green

In [29]:
finalDF.drop(["Aircraft"], axis=1, inplace=True)
finalDF

,Airline Code,Aircraft Registration,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11264563,zh-csz,b-225k,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,29 Sep 2024,Shenzhen(SZX),Wuxi(WUX),ZH9801,2:12,07:20,07:43,09:35,Landed 09:55,yellow
11264564,zh-csz,b-225k,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Chongqing(CKG),Shenzhen(SZX),ZH9426,1:41,20:25,00:01,22:40,Landed 01:42,red
11264565,zh-csz,b-225k,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Chongqing(CKG),ZH9425,1:54,17:05,21:05,19:15,Landed 22:59,red
11264566,zh-csz,b-225k,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Nanjing(NKG),Shenzhen(SZX),ZH8982,2:28,14:55,16:34,17:20,Landed 19:02,red
11264567,zh-csz,b-225k,Shenzhen Airlines,Shenzhen Airlines,B38M,7820BC,61703,2 years,28 Sep 2024,Shenzhen(SZX),Nanjing(NKG),ZH8981,1:57,11:10,11:31,13:25,Landed 13:27,green

In [30]:
finalDF1.rename(columns={"planeID": "Aircraft Registration"}, inplace=True)
finalDF1

,Aircraft Registration,aircraftTypeCode,operator,code,modeS,serialNumber,age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,ONTIME,STATUS
0,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,14 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:14,12:15 AM,12:54 AM,8:10 AM,green,Landed 8:08 AM
1,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Bangkok (BKK),NQ1,6:47,5:35 PM,5:53 PM,11:00 PM,green,Landed 10:40 PM
2,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Seoul (ICN),Tokyo (NRT),NQ22,1:48,1:40 PM,1:58 PM,4:00 PM,green,Landed 3:46 PM
3,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Seoul (ICN),NQ21,2:20,9:50 AM,10:02 AM,12:30 PM,green,Landed 12:22 PM
4,JA801A,B788,Air Japan,NQ / AJX,86CE6C,34488.0,13 years,13 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:04,12:15 AM,1:12 AM,8:10 AM,green,Landed 8:16 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779020,9V-SDA,B78X,Singapore Airlines,SQ / SIA,76CC81,67157.0,Brand new,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,7:30 PM,1:19 PM,6:30 PM,gray,Landed 6:30 PM
779021,9V-SDA,B78X,Singapore Airlines,SQ / SIA,76CC81,67157.0,Brand new,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,8:00 AM,8:34 AM,11:55 AM,gray,Landed 11:55 AM
779022,9V-SDA,B78X,Singapore Airlines,SQ / SIA,76CC81,67157.0,Brand new,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,1:30 PM,2:24 PM,4:27 PM,gray,Landed 4:27 PM
779023,9V-SDA,B78X,Singapore Airlines,SQ / SIA,76CC81,67157.0,Brand new,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,6:45 PM,7:05 PM,7:02 PM,yellow,Landed 7:18 PM
779024,9V-SDA,B78X,Singapore Airlines,SQ / SIA,76CC81,67157.0,Brand new,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45 AM,1:23 PM,1:17 PM,gray,Landed 1:17 PM

In [31]:
finalDF1.rename(columns={"code": "Airline Code"}, inplace=True)

In [36]:
finalDF.to_csv('DataMARCUSVS.csv', index=False)
finalDF1.to_csv('DataZF.csv', index=False)

In [42]:
finalDF1 = pd.read_csv('DataZF.csv')

In [44]:
finalDF1
finalDF1['Airline Code'] = finalDF1['Airline Code'].str.replace(r'\s*/\s*', '-', regex=True).str.strip()

In [47]:
finalDF1.rename(columns={"aircraftTypeCode": "Type Code",
                         "modeS": "Mode S"}, inplace=True)

In [51]:
finalDF1.head()

,Aircraft Registration,Type Code,operator,Airline Code,Mode S,serialNumber,age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,ONTIME,STATUS
0,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,14 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:14,12:15 AM,12:54 AM,8:10 AM,green,Landed 8:08 AM
1,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Bangkok (BKK),NQ1,6:47,5:35 PM,5:53 PM,11:00 PM,green,Landed 10:40 PM
2,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Seoul (ICN),Tokyo (NRT),NQ22,1:48,1:40 PM,1:58 PM,4:00 PM,green,Landed 3:46 PM
3,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Seoul (ICN),NQ21,2:20,9:50 AM,10:02 AM,12:30 PM,green,Landed 12:22 PM
4,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:04,12:15 AM,1:12 AM,8:10 AM,green,Landed 8:16 AM

In [53]:
finalDF.head()

,Airline Code,Aircraft Registration,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green

In [54]:
finalDF1.rename(columns={"age": "Age",
                         "ONTIME" : "Color Code"}, inplace=True)
finalDF1.head()

,Aircraft Registration,Type Code,operator,Airline Code,Mode S,serialNumber,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,Color Code,STATUS
0,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,14 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:14,12:15 AM,12:54 AM,8:10 AM,green,Landed 8:08 AM
1,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Bangkok (BKK),NQ1,6:47,5:35 PM,5:53 PM,11:00 PM,green,Landed 10:40 PM
2,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Seoul (ICN),Tokyo (NRT),NQ22,1:48,1:40 PM,1:58 PM,4:00 PM,green,Landed 3:46 PM
3,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Seoul (ICN),NQ21,2:20,9:50 AM,10:02 AM,12:30 PM,green,Landed 12:22 PM
4,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:04,12:15 AM,1:12 AM,8:10 AM,green,Landed 8:16 AM

In [55]:
finalDF1.rename(columns={"serialNumber": "Serial Number"}, inplace=True)

In [57]:
finalDF1.to_csv('DataZF.csv', index=False)

In [58]:
finalDF1.head()

,Aircraft Registration,Type Code,operator,Airline Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,Color Code,STATUS
0,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,14 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:14,12:15 AM,12:54 AM,8:10 AM,green,Landed 8:08 AM
1,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Bangkok (BKK),NQ1,6:47,5:35 PM,5:53 PM,11:00 PM,green,Landed 10:40 PM
2,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Seoul (ICN),Tokyo (NRT),NQ22,1:48,1:40 PM,1:58 PM,4:00 PM,green,Landed 3:46 PM
3,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Tokyo (NRT),Seoul (ICN),NQ21,2:20,9:50 AM,10:02 AM,12:30 PM,green,Landed 12:22 PM
4,JA801A,B788,Air Japan,NQ-AJX,86CE6C,34488.0,13 years,13 Jan 2025,Bangkok (BKK),Tokyo (NRT),NQ2,5:04,12:15 AM,1:12 AM,8:10 AM,green,Landed 8:16 AM

In [59]:
finalDF.head()

,Airline Code,Aircraft Registration,Airline,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green

In [60]:
finalDF.drop(["Airline"], axis=1, inplace=True) 
finalDF1.rename(columns={"operator": "Operator"}, inplace=True)

In [64]:
finalDF1.to_csv('DataZF.csv', index=False) 
finalDF.to_csv('DataMARCUSVS.csv', index=False)

In [67]:
finalDF1.columns

Index(['Aircraft Registration', 'Type Code', 'Operator', 'Airline Code',
       'Mode S', 'Serial Number', 'Age', 'DATE', 'FROM', 'TO', 'FLIGHT',
       'FLIGHT TIME', 'STD', 'ATD', 'STA', 'Color Code', 'STATUS'],
      dtype='object')

In [69]:
finalDF.columns

Index(['Airline Code', 'Aircraft Registration', 'Operator', 'Type Code',
       'Mode S', 'Serial Number', 'Age', 'DATE', 'FROM', 'TO', 'FLIGHT',
       'FLIGHT TIME', 'STD', 'ATD', 'STA', 'STATUS', 'Color Code'],
      dtype='object')

MERGED BOTH FINALIZED DATA

In [ ]:
MERGED_DF = pd.concat([finalDF, finalDF1], ignore_index=True).drop_duplicates() 
MERGED_DF

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\778877351.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  MERGED_DF = pd.read_csv('MERGED_DATA.csv')

In [71]:
MERGED_DF.to_csv('MERGED_DATA.csv', index=False)

In [ ]:
MERGED_DF = pd.read_csv('SCRAPED_MERGED_DATA.csv')

C:\Users\yugik\AppData\Local\Temp\ipykernel_51640\1585246776.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  MERGED_DF = pd.read_csv('SCRAPED_MERGED_DATA.csv')

array(['green', 'red', 'yellow', 'gray', nan], dtype=object)

In [78]:
MERGED_DF

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038808,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,7:30 PM,1:19 PM,6:30 PM,Landed 6:30 PM,gray
12038809,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,8:00 AM,8:34 AM,11:55 AM,Landed 11:55 AM,gray
12038810,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,1:30 PM,2:24 PM,4:27 PM,Landed 4:27 PM,gray
12038811,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,6:45 PM,7:05 PM,7:02 PM,Landed 7:18 PM,yellow
12038812,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45 AM,1:23 PM,1:17 PM,Landed 1:17 PM,gray

In [81]:
merged = MERGED_DF[MERGED_DF['Airline Code'] != 'jl-jal']

In [83]:
merged.to_csv('SCRAPED_MERGED_DATA.csv', index=False)

In [84]:
merged

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038808,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,7:30 PM,1:19 PM,6:30 PM,Landed 6:30 PM,gray
12038809,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,8:00 AM,8:34 AM,11:55 AM,Landed 11:55 AM,gray
12038810,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,1:30 PM,2:24 PM,4:27 PM,Landed 4:27 PM,gray
12038811,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,6:45 PM,7:05 PM,7:02 PM,Landed 7:18 PM,yellow
12038812,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45 AM,1:23 PM,1:17 PM,Landed 1:17 PM,gray

THIS PART OF THE CODE HAPPENS AFTER WE REMOVED THE DUPS
SO WE ARE USING SCRAPED_MERGED_DATA_RMVDUP.CSV

In [9]:
import modin.pandas as pd
from tqdm import tqdm

In [10]:

df = pd.read_csv('SCRAPED_MERGED_DATA_RMVDUP.csv')

In [6]:
df

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45,17:53,21:55,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35,12:47,17:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40,07:49,11:25,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10,21:12,22:40,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55,15:56,18:05,Landed 17:41,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844337,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,7:30 PM,1:19 PM,6:30 PM,Landed 6:30 PM,gray
11844338,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,8:00 AM,8:34 AM,11:55 AM,Landed 11:55 AM,gray
11844339,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,1:30 PM,2:24 PM,4:27 PM,Landed 4:27 PM,gray
11844340,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,6:45 PM,7:05 PM,7:02 PM,Landed 7:18 PM,yellow
11844341,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45 AM,1:23 PM,1:17 PM,Landed 1:17 PM,gray

CONVERT STA STD AND ATD TO DATETIME 24 HOURS FORMAT

In [ ]:


# Columns to convert
timeCols = ['STD', 'STA', 'ATD']

tqdm.pandas(desc='Processing rows')

# Function to convert time
def convert_mixed_time(time):
    if pd.isnull(time) or str(time).strip() == '':
        return None
    try:
        # Attempt 24-hour format
        return pd.to_datetime(time, format='%H:%M', errors='raise').time()
    except:
        try:
            # Attempt 24-hour format with seconds
            return pd.to_datetime(time, format='%H:%M:%S', errors='raise').time()
        except:
            try:
                # Attempt 12-hour format with AM/PM
                return pd.to_datetime(time, format='%I:%M %p', errors='raise').time()
            except:
                return None

# Apply the function to each time column
for col in timeCols:
     df[col] = [convert_mixed_time(t) for t in tqdm(df[col], desc=f"Converting {col}")]   
    
df

Converting STD:  25%|██▍       | 2906749/11844342 [03:14<10:41, 13932.34it/s]

In [4]:
df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

In [12]:
df.head()

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45:00,17:53:00,21:55:00,Landed 21:48,green
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35:00,12:47:00,17:00:00,Landed 16:46,green
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40:00,07:49:00,11:25:00,Landed 10:54,green
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10:00,21:12:00,22:40:00,Landed 00:21,red
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55:00,15:56:00,18:05:00,Landed 17:41,green

Create ATA from Status

In [14]:
df['ATA'] = (
    df['STATUS']
   .str.extract(r'Landed\s(\d{1,2}:\d{2}(?:\s?(?:AM|PM))?)')[0]  # Extract time
   .apply(convert_mixed_time)  # Convert to time 
   
)
df['ATA'] = df['ATA'].apply(lambda x: x.strftime('%H:%M:%S') if x else None) 
df

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code,ATA
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45:00,17:53:00,21:55:00,Landed 21:48,green,21:48:00
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35:00,12:47:00,17:00:00,Landed 16:46,green,16:46:00
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40:00,07:49:00,11:25:00,Landed 10:54,green,10:54:00
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10:00,21:12:00,22:40:00,Landed 00:21,red,00:21:00
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5 years,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55:00,15:56:00,18:05:00,Landed 17:41,green,17:41:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844337,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,19:30:00,13:19:00,18:30:00,Landed 6:30 PM,gray,18:30:00
11844338,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,08:00:00,08:34:00,11:55:00,Landed 11:55 AM,gray,11:55:00
11844339,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,13:30:00,14:24:00,16:27:00,Landed 4:27 PM,gray,16:27:00
11844340,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,18:45:00,19:05:00,19:02:00,Landed 7:18 PM,yellow,19:18:00
11844341,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,Brand new,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45:00,13:23:00,13:17:00,Landed 1:17 PM,gray,13:17:00

In [15]:
df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

Convert the Age column to Age (in years) so it can be in integer type  
Remove the word "years" and extract only the numeric portion.  
Convert "Brand new" to 0.  
Convert '-' and NaN to None (or NaN, depending on your preference).  
Convert the resulting column to a numeric type.

In [5]:
df['Age'].unique()

array(['5 years', '4 years', '3 years', '2 years', '7 years', '6 years',
       '1 year', '19 years', '20 years', '17 years', '16 years',
       '15 years', '13 years', '12 years', '11 years', '10 years',
       '9 years', '14 years', '8 years', '21 years', '18 years',
       'Brand new', nan, '22 years', '23 years', '24 years', '28 years',
       '27 years', '29 years', '26 years', '33 years', '32 years',
       '30 years', '31 years', '25 years', '34 years', '35 years', '-'],
      dtype=object)

In [6]:
# Clean 'Age' column
def clean_age(value):
    if pd.isna(value) or value == '-':
        return None  # Convert NaN or '-' to None
    if value == 'Brand new':
        return 0  # Convert 'Brand new' to 0
    # Remove 'years' and 'year', then convert to integer
    return int(value.split()[0]) if value.split()[0].isdigit() else None

# Apply the cleaning function
df['Age'] = df['Age'].apply(clean_age)

# Convert to numeric dtype for LightGBM compatibility
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age,DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code,ATA
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,3:56,17:45:00,17:53:00,21:55:00,Landed 21:48,green,21:48:00
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,3:59,12:35:00,12:47:00,17:00:00,Landed 16:46,green,16:46:00
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,3:05,07:40:00,07:49:00,11:25:00,Landed 10:54,green,10:54:00
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,3:10,19:10:00,21:12:00,22:40:00,Landed 00:21,red,00:21:00
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,1:46,15:55:00,15:56:00,18:05:00,Landed 17:41,green,17:41:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844337,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,6:11,19:30:00,13:19:00,18:30:00,Landed 6:30 PM,gray,18:30:00
11844338,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,14:21,08:00:00,08:34:00,11:55:00,Landed 11:55 AM,gray,11:55:00
11844339,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,3:04,13:30:00,14:24:00,16:27:00,Landed 4:27 PM,gray,16:27:00
11844340,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,0:14,18:45:00,19:05:00,19:02:00,Landed 7:18 PM,yellow,19:18:00
11844341,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,0:54,11:45:00,13:23:00,13:17:00,Landed 1:17 PM,gray,13:17:00

rename Age to Age(Years)

In [ ]:
df.rename(columns={"Age": "Age(years)"}, inplace=True)
print(df)

df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

Convert FLIGHT TIME TO FLIGHT TIME (mins)

In [20]:
# Ensure the column is string
df['FLIGHT TIME'] = df['FLIGHT TIME'].astype(str)

# Apply the lambda only to rows matching the HH:MM pattern
valid_mask = df['FLIGHT TIME'].str.match(r'^\d{1,2}:\d{2}$', na=False)

valid_mask

0           True
1           True
2           True
3           True
4           True
            ...
11844337    True
11844338    True
11844339    True
11844340    True
11844341    True
Name: FLIGHT TIME, Length: 11844342, dtype: bool

In [21]:
df.loc[valid_mask, 'FLIGHT TIME'] = df[valid_mask]['FLIGHT TIME'].apply(lambda x: int(x.split(':')[0]) * 60 + int(x.split(':')[1]))
df

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age(years),DATE,FROM,TO,FLIGHT,FLIGHT TIME,STD,ATD,STA,STATUS,Color Code,ATA
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,236.0,17:45:00,17:53:00,21:55:00,Landed 21:48,green,21:48:00
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,239.0,12:35:00,12:47:00,17:00:00,Landed 16:46,green,16:46:00
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,185.0,07:40:00,07:49:00,11:25:00,Landed 10:54,green,10:54:00
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,190.0,19:10:00,21:12:00,22:40:00,Landed 00:21,red,00:21:00
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,106.0,15:55:00,15:56:00,18:05:00,Landed 17:41,green,17:41:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844337,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,371.0,19:30:00,13:19:00,18:30:00,Landed 6:30 PM,gray,18:30:00
11844338,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,861.0,08:00:00,08:34:00,11:55:00,Landed 11:55 AM,gray,11:55:00
11844339,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,184.0,13:30:00,14:24:00,16:27:00,Landed 4:27 PM,gray,16:27:00
11844340,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,14.0,18:45:00,19:05:00,19:02:00,Landed 7:18 PM,yellow,19:18:00
11844341,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,54.0,11:45:00,13:23:00,13:17:00,Landed 1:17 PM,gray,13:17:00

In [26]:
# Convert to float, invalid conversions become NaN
df['FLIGHT TIME'] = pd.to_numeric(df['FLIGHT TIME'], errors='coerce')

# Confirm results
print(df['FLIGHT TIME'].dtype)
print(df['FLIGHT TIME'].isna().sum())

float64
279261

In [ ]:
df.rename(columns={"FLIGHT TIME": "FLIGHT TIME(mins)"}, inplace=True)
df

df[df['FLIGHT TIME(mins)'].isna()]  

df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age(years),DATE,FROM,TO,FLIGHT,FLIGHT TIME(mins),STD,ATD,STA,STATUS,Color Code,ATA
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,236.0,17:45:00,17:53:00,21:55:00,Landed 21:48,green,21:48:00
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,239.0,12:35:00,12:47:00,17:00:00,Landed 16:46,green,16:46:00
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,185.0,07:40:00,07:49:00,11:25:00,Landed 10:54,green,10:54:00
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,190.0,19:10:00,21:12:00,22:40:00,Landed 00:21,red,00:21:00
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,106.0,15:55:00,15:56:00,18:05:00,Landed 17:41,green,17:41:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844337,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,371.0,19:30:00,13:19:00,18:30:00,Landed 6:30 PM,gray,18:30:00
11844338,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,861.0,08:00:00,08:34:00,11:55:00,Landed 11:55 AM,gray,11:55:00
11844339,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,184.0,13:30:00,14:24:00,16:27:00,Landed 4:27 PM,gray,16:27:00
11844340,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,14.0,18:45:00,19:05:00,19:02:00,Landed 7:18 PM,yellow,19:18:00
11844341,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,54.0,11:45:00,13:23:00,13:17:00,Landed 1:17 PM,gray,13:17:00

In [2]:
df = pd.read_csv('SCRAPED_MERGED_DATA_PROCESSED.csv') 
df

C:\Users\yugik\AppData\Local\Temp\ipykernel_101804\3483316428.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('SCRAPED_MERGED_DATA_PROCESSED.csv')

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age(years),DATE,FROM,TO,FLIGHT,FLIGHT TIME(mins),STD,ATD,STA,STATUS,Color Code,ATA
0,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Yining(YIN),Chengdu(TFU),3U6592,236.0,17:45:00,17:53:00,21:55:00,Landed 21:48,green,21:48:00
1,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Chengdu(TFU),Yining(YIN),3U6591,239.0,12:35:00,12:47:00,17:00:00,Landed 16:46,green,16:46:00
2,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,31 Aug 2024,Urumqi(URC),Chengdu(TFU),3U6518,185.0,07:40:00,07:49:00,11:25:00,Landed 10:54,green,10:54:00
3,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Chengdu(TFU),Urumqi(URC),3U6517,190.0,19:10:00,21:12:00,22:40:00,Landed 00:21,red,00:21:00
4,3u-csc,b-30cr,Sichuan Airlines,A20N,781848,8873.0,5.0,30 Aug 2024,Zhanjiang(ZHA),Chengdu(TFU),3U6780,106.0,15:55:00,15:56:00,18:05:00,Landed 17:41,green,17:41:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844167,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,25 Sep 2024,Nagoya (NGO),Singapore (SIN),SQ8879,371.0,19:30:00,13:19:00,18:30:00,Landed 6:30 PM,gray,18:30:00
11844168,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,24 Sep 2024,Charleston (CHS),Nagoya (NGO),SQ8879,861.0,08:00:00,08:34:00,11:55:00,Landed 11:55 AM,gray,11:55:00
11844169,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,10 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,184.0,13:30:00,14:24:00,16:27:00,Landed 4:27 PM,gray,16:27:00
11844170,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,01 Sep 2024,Charleston (CHS),Charleston (CHS),BOE26,14.0,18:45:00,19:05:00,19:02:00,Landed 7:18 PM,yellow,19:18:00
11844171,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,31 Aug 2024,Charleston (CHS),Charleston (CHS),BOE26,54.0,11:45:00,13:23:00,13:17:00,Landed 1:17 PM,gray,13:17:00

Removed "Sorry, but we could not find data for specified flight" from the data

In [5]:
#df = pd.read_csv('SCRAPED_MERGED_DATA_PROCESSED.csv') 
print (len(df)) 
# Create mask for error messages
df = df[~df['DATE'].str.contains('Sorry, but we could not find data for specified flight', na=False)]
print (len(df))

11844342
11844172

In [6]:
df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

Remove those extra encoding on some rows in the serial number with the \u

In [12]:
# rows_with_62199 = df[df['Serial Number'].str.contains('62199', na=False)]
# print (rows_with_62199) 
# # df['Serial Number'] = df['Serial Number'].apply(lambda x: re.sub(r'\D', '', str(x)) if pd.notna(x) else '')
for index, val in df['Serial Number'].items():
    valStr = str(val) 
    for c in valStr: 
        if ord (c) > 127:
            print (f"row {index} : hidden character {c} : {val}")

row 5163979 : hidden character ‬ : 62199‬
row 5163980 : hidden character ‬ : 62199‬
row 5163981 : hidden character ‬ : 62199‬
row 5163982 : hidden character ‬ : 62199‬
row 5163983 : hidden character ‬ : 62199‬
row 5163984 : hidden character ‬ : 62199‬
row 5163985 : hidden character ‬ : 62199‬
row 5163986 : hidden character ‬ : 62199‬
row 5163987 : hidden character ‬ : 62199‬
row 5163988 : hidden character ‬ : 62199‬
row 5163989 : hidden character ‬ : 62199‬
row 5163990 : hidden character ‬ : 62199‬
row 5163991 : hidden character ‬ : 62199‬
row 5163992 : hidden character ‬ : 62199‬
row 5163993 : hidden character ‬ : 62199‬
row 5163994 : hidden character ‬ : 62199‬
row 5163995 : hidden character ‬ : 62199‬
row 5163996 : hidden character ‬ : 62199‬
row 5163997 : hidden character ‬ : 62199‬
row 5163998 : hidden character ‬ : 62199‬
row 5163999 : hidden character ‬ : 62199‬
row 5164000 : hidden character ‬ : 62199‬
row 5164001 : hidden character ‬ : 62199‬
row 5164002 : hidden character ‬ : 62199‬
row 5164003 : hidden character ‬ : 62199‬
row 5164004 : hidden character ‬ : 62199‬
row 5164005 : hidden character ‬ : 62199‬
row 5164006 : hidden character ‬ : 62199‬
row 5164007 : hidden character ‬ : 62199‬
row 5164008 : hidden character ‬ : 62199‬
row 5164009 : hidden character ‬ : 62199‬
row 5164010 : hidden character ‬ : 62199‬
row 5164011 : hidden character ‬ : 62199‬
row 5164012 : hidden character ‬ : 62199‬
row 5164013 : hidden character ‬ : 62199‬
row 5164014 : hidden character ‬ : 62199‬
row 5164015 : hidden character ‬ : 62199‬
row 5164016 : hidden character ‬ : 62199‬
row 5164017 : hidden character ‬ : 62199‬
row 5164018 : hidden character ‬ : 62199‬
row 5164019 : hidden character ‬ : 62199‬
row 5164020 : hidden character ‬ : 62199‬
row 5164021 : hidden character ‬ : 62199‬
row 5164022 : hidden character ‬ : 62199‬
row 5164023 : hidden character ‬ : 62199‬
row 5164024 : hidden character ‬ : 62199‬
row 5164025 : hidden character ‬ : 62199‬
row 5164026 : hidden character ‬ : 62199‬
row 5164027 : hidden character ‬ : 62199‬
row 5164028 : hidden character ‬ : 62199‬
row 5164029 : hidden character ‬ : 62199‬
row 5164030 : hidden character ‬ : 62199‬
row 5164031 : hidden character ‬ : 62199‬
row 5164032 : hidden character ‬ : 62199‬
row 5164033 : hidden character ‬ : 62199‬
row 5164034 : hidden character ‬ : 62199‬
row 5164035 : hidden character ‬ : 62199‬
row 5164036 : hidden character ‬ : 62199‬
row 5164037 : hidden character ‬ : 62199‬
row 5164038 : hidden character ‬ : 62199‬
row 5164039 : hidden character ‬ : 62199‬
row 5164040 : hidden character ‬ : 62199‬
row 5164041 : hidden character ‬ : 62199‬
row 5164042 : hidden character ‬ : 62199‬
row 5164043 : hidden character ‬ : 62199‬
row 5164044 : hidden character ‬ : 62199‬
row 5164045 : hidden character ‬ : 62199‬
row 5164046 : hidden character ‬ : 62199‬
row 5164047 : hidden character ‬ : 62199‬
row 5164048 : hidden character ‬ : 62199‬
row 5164049 : hidden character ‬ : 62199‬
row 5164050 : hidden character ‬ : 62199‬
row 5164051 : hidden character ‬ : 62199‬
row 5164052 : hidden character ‬ : 62199‬
row 5164053 : hidden character ‬ : 62199‬
row 5164054 : hidden character ‬ : 62199‬
row 5164055 : hidden character ‬ : 62199‬
row 5164056 : hidden character ‬ : 62199‬
row 5164057 : hidden character ‬ : 62199‬
row 5164058 : hidden character ‬ : 62199‬
row 5164059 : hidden character ‬ : 62199‬
row 5164060 : hidden character ‬ : 62199‬
row 5164061 : hidden character ‬ : 62199‬
row 5164062 : hidden character ‬ : 62199‬
row 5164063 : hidden character ‬ : 62199‬
row 5164064 : hidden character ‬ : 62199‬
row 5164065 : hidden character ‬ : 62199‬
row 5164066 : hidden character ‬ : 62199‬
row 5164067 : hidden character ‬ : 62199‬
row 5164068 : hidden character ‬ : 62199‬
row 5164069 : hidden character ‬ : 62199‬
row 5164070 : hidden character ‬ : 62199‬
row 5164071 : hidden character ‬ : 62199‬
row 5164072 : hidden character ‬ : 62199‬
row 5164073 : hidden character ‬ : 62199‬
row 5164074 : hidden character ‬ : 62199‬
row 5164075 : hidden character ‬ : 62199‬
row 5164076 : hidden character ‬ : 62199‬
row 5164077 : hidden character ‬ : 62199‬
row 5164078 : hidden character ‬ : 62199‬
row 5164079 : hidden character ‬ : 62199‬
row 5164080 : hidden character ‬ : 62199‬
row 5164081 : hidden character ‬ : 62199‬
row 5164082 : hidden character ‬ : 62199‬
row 5164083 : hidden character ‬ : 62199‬
row 5164084 : hidden character ‬ : 62199‬
row 5164085 : hidden character ‬ : 62199‬
row 5164086 : hidden character ‬ : 62199‬
row 5164087 : hidden character ‬ : 62199‬
row 5164088 : hidden character ‬ : 62199‬
row 5164089 : hidden character ‬ : 62199‬
row 5164090 : hidden character ‬ : 62199‬
row 5164091 : hidden character ‬ : 62199‬
row 5164092 : hidden character ‬ : 62199‬
row 5164093 : hidden character ‬ : 62199‬
row 5164094 : hidden character ‬ : 62199‬
row 5164095 : hidden character ‬ : 62199‬
row 5164096 : hidden character ‬ : 62199‬
row 5164097 : hidden character ‬ : 62199‬
row 5164098 : hidden character ‬ : 62199‬
row 5164099 : hidden character ‬ : 62199‬
row 5164100 : hidden character ‬ : 62199‬
row 5164101 : hidden character ‬ : 62199‬
row 5164102 : hidden character ‬ : 62199‬
row 5164103 : hidden character ‬ : 62199‬
row 5164104 : hidden character ‬ : 62199‬
row 5164105 : hidden character ‬ : 62199‬
row 5164106 : hidden character ‬ : 62199‬
row 5164107 : hidden character ‬ : 62199‬
row 5164108 : hidden character ‬ : 62199‬
row 5164109 : hidden character ‬ : 62199‬
row 5164110 : hidden character ‬ : 62199‬
row 5164111 : hidden character ‬ : 62199‬
row 5164112 : hidden character ‬ : 62199‬
row 5164113 : hidden character ‬ : 62199‬
row 5164114 : hidden character ‬ : 62199‬
row 5164115 : hidden character ‬ : 62199‬
row 5164116 : hidden character ‬ : 62199‬
row 5164117 : hidden character ‬ : 62199‬
row 5164118 : hidden character ‬ : 62199‬
row 5164119 : hidden character ‬ : 62199‬
row 5164120 : hidden character ‬ : 62199‬
row 5164121 : hidden character ‬ : 62199‬
row 5164122 : hidden character ‬ : 62199‬
row 5164123 : hidden character ‬ : 62199‬
row 5164124 : hidden character ‬ : 62199‬
row 5164125 : hidden character ‬ : 62199‬
row 5164126 : hidden character ‬ : 62199‬
row 5164127 : hidden character ‬ : 62199‬
row 5164128 : hidden character ‬ : 62199‬
row 5164129 : hidden character ‬ : 62199‬
row 5164130 : hidden character ‬ : 62199‬
row 5164131 : hidden character ‬ : 62199‬
row 5164132 : hidden character ‬ : 62199‬
row 5164133 : hidden character ‬ : 62199‬
row 5164134 : hidden character ‬ : 62199‬
row 5164135 : hidden character ‬ : 62199‬
row 5164136 : hidden character ‬ : 62199‬
row 5164137 : hidden character ‬ : 62199‬
row 5164138 : hidden character ‬ : 62199‬
row 5164139 : hidden character ‬ : 62199‬
row 5164140 : hidden character ‬ : 62199‬
row 5164141 : hidden character ‬ : 62199‬
row 5164142 : hidden character ‬ : 62199‬
row 5164143 : hidden character ‬ : 62199‬
row 5164144 : hidden character ‬ : 62199‬
row 5164145 : hidden character ‬ : 62199‬
row 5164146 : hidden character ‬ : 62199‬
row 5164147 : hidden character ‬ : 62199‬
row 5164148 : hidden character ‬ : 62199‬
row 5164149 : hidden character ‬ : 62199‬
row 5164150 : hidden character ‬ : 62199‬
row 5164151 : hidden character ‬ : 62199‬
row 5164152 : hidden character ‬ : 62199‬
row 5164153 : hidden character ‬ : 62199‬
row 5164154 : hidden character ‬ : 62199‬
row 5164155 : hidden character ‬ : 62199‬
row 5164156 : hidden character ‬ : 62199‬
row 5164157 : hidden character ‬ : 62199‬
row 5164158 : hidden character ‬ : 62199‬
row 5164159 : hidden character ‬ : 62199‬
row 5164160 : hidden character ‬ : 62199‬
row 5164161 : hidden character ‬ : 62199‬
row 5164162 : hidden character ‬ : 62199‬
row 5164163 : hidden character ‬ : 62199‬
row 5164164 : hidden character ‬ : 62199‬
row 5164165 : hidden character ‬ : 62199‬
row 5164166 : hidden character ‬ : 62199‬
row 5164167 : hidden character ‬ : 62199‬
row 5164168 : hidden character ‬ : 62199‬
row 5164169 : hidden character ‬ : 62199‬
row 5164170 : hidden character ‬ : 62199‬
row 5164171 : hidden character ‬ : 62199‬
row 5164172 : hidden character ‬ : 62199‬
row 5164173 : hidden character ‬ : 62199‬
row 5164174 : hidden character ‬ : 62199‬
row 5164175 : hidden character ‬ : 62199‬
row 5164176 : hidden character ‬ : 62199‬
row 5164177 : hidden character ‬ : 62199‬
row 5164178 : hidden character ‬ : 62199‬
row 5164179 : hidden character ‬ : 62199‬
row 5164180 : hidden character ‬ : 62199‬
row 5164181 : hidden character ‬ : 62199‬
row 5164182 : hidden character ‬ : 62199‬
row 5164183 : hidden character ‬ : 62199‬
row 5164184 : hidden character ‬ : 62199‬
row 5164185 : hidden character ‬ : 62199‬
row 5164186 : hidden character ‬ : 62199‬
row 5164187 : hidden character ‬ : 62199‬
row 5164188 : hidden character ‬ : 62199‬
row 5164189 : hidden character ‬ : 62199‬
row 5164190 : hidden character ‬ : 62199‬
row 5164191 : hidden character ‬ : 62199‬
row 5164192 : hidden character ‬ : 62199‬
row 5164193 : hidden character ‬ : 62199‬
row 5164194 : hidden character ‬ : 62199‬
row 5164195 : hidden character ‬ : 62199‬
row 5164196 : hidden character ‬ : 62199‬
row 5164197 : hidden character ‬ : 62199‬
row 5164198 : hidden character ‬ : 62199‬
row 5164199 : hidden character ‬ : 62199‬
row 5164200 : hidden character ‬ : 62199‬
row 5164201 : hidden character ‬ : 62199‬
row 5164202 : hidden character ‬ : 62199‬
row 5164203 : hidden character ‬ : 62199‬
row 5164204 : hidden character ‬ : 62199‬
row 5164205 : hidden character ‬ : 62199‬
row 5164206 : hidden character ‬ : 62199‬
row 5164207 : hidden character ‬ : 62199‬
row 5164208 : hidden character ‬ : 62199‬
row 5164209 : hidden character ‬ : 62199‬
row 5164210 : hidden character ‬ : 62199‬
row 5164211 : hidden character ‬ : 62199‬
row 5164212 : hidden character ‬ : 62199‬
row 5164213 : hidden character ‬ : 62199‬
row 5164214 : hidden character ‬ : 62199‬
row 5164215 : hidden character ‬ : 62199‬
row 5164216 : hidden character ‬ : 62199‬
row 5164217 : hidden character ‬ : 62199‬
row 5164218 : hidden character ‬ : 62199‬
row 5164219 : hidden character ‬ : 62199‬
row 5164220 : hidden character ‬ : 62199‬
row 5164221 : hidden character ‬ : 62199‬
row 5164222 : hidden character ‬ : 62199‬
row 5164223 : hidden character ‬ : 62199‬
row 5164224 : hidden character ‬ : 62199‬
row 5164225 : hidden character ‬ : 62199‬
row 5164226 : hidden character ‬ : 62199‬
row 5164227 : hidden character ‬ : 62199‬
row 5164228 : hidden character ‬ : 62199‬
row 5164229 : hidden character ‬ : 62199‬
row 5164230 : hidden character ‬ : 62199‬
row 5164231 : hidden character ‬ : 62199‬
row 5164232 : hidden character ‬ : 62199‬
row 5164233 : hidden character ‬ : 62199‬
row 5164234 : hidden character ‬ : 62199‬
row 5164235 : hidden character ‬ : 62199‬
row 5164236 : hidden character ‬ : 62199‬
row 5164237 : hidden character ‬ : 62199‬
row 5164238 : hidden character ‬ : 62199‬
row 5164239 : hidden character ‬ : 62199‬
row 5164240 : hidden character ‬ : 62199‬
row 5164241 : hidden character ‬ : 62199‬
row 5164242 : hidden character ‬ : 62199‬
row 5164243 : hidden character ‬ : 62199‬
row 5164244 : hidden character ‬ : 62199‬
row 5164245 : hidden character ‬ : 62199‬
row 5164246 : hidden character ‬ : 62199‬
row 5164247 : hidden character ‬ : 62199‬
row 5164248 : hidden character ‬ : 62199‬
row 5164249 : hidden character ‬ : 62199‬
row 5164250 : hidden character ‬ : 62199‬
row 5164251 : hidden character ‬ : 62199‬
row 5164252 : hidden character ‬ : 62199‬
row 5164253 : hidden character ‬ : 62199‬
row 5164254 : hidden character ‬ : 62199‬
row 5164255 : hidden character ‬ : 62199‬
row 5164256 : hidden character ‬ : 62199‬
row 5164257 : hidden character ‬ : 62199‬
row 5164258 : hidden character ‬ : 62199‬
row 5164259 : hidden character ‬ : 62199‬
row 5164260 : hidden character ‬ : 62199‬
row 5164261 : hidden character ‬ : 62199‬
row 5164262 : hidden character ‬ : 62199‬
row 5164263 : hidden character ‬ : 62199‬
row 5164264 : hidden character ‬ : 62199‬
row 5164265 : hidden character ‬ : 62199‬
row 5164266 : hidden character ‬ : 62199‬
row 5164267 : hidden character ‬ : 62199‬
row 5164268 : hidden character ‬ : 62199‬
row 5164269 : hidden character ‬ : 62199‬
row 5164270 : hidden character ‬ : 62199‬
row 5164271 : hidden character ‬ : 62199‬
row 5164272 : hidden character ‬ : 62199‬
row 5164273 : hidden character ‬ : 62199‬
row 5164274 : hidden character ‬ : 62199‬
row 5164275 : hidden character ‬ : 62199‬
row 5164276 : hidden character ‬ : 62199‬
row 5164277 : hidden character ‬ : 62199‬
row 5164278 : hidden character ‬ : 62199‬
row 5164279 : hidden character ‬ : 62199‬
row 5164280 : hidden character ‬ : 62199‬
row 5164281 : hidden character ‬ : 62199‬
row 5164282 : hidden character ‬ : 62199‬
row 5164283 : hidden character ‬ : 62199‬
row 5164284 : hidden character ‬ : 62199‬
row 5164285 : hidden character ‬ : 62199‬
row 5164286 : hidden character ‬ : 62199‬
row 5164287 : hidden character ‬ : 62199‬
row 5164288 : hidden character ‬ : 62199‬
row 5164289 : hidden character ‬ : 62199‬
row 5164290 : hidden character ‬ : 62199‬
row 5164291 : hidden character ‬ : 62199‬
row 5164292 : hidden character ‬ : 62199‬
row 5164293 : hidden character ‬ : 62199‬
row 5164294 : hidden character ‬ : 62199‬
row 5164295 : hidden character ‬ : 62199‬
row 5164296 : hidden character ‬ : 62199‬
row 5164297 : hidden character ‬ : 62199‬
row 5164298 : hidden character ‬ : 62199‬
row 5164299 : hidden character ‬ : 62199‬
row 5164300 : hidden character ‬ : 62199‬
row 5164301 : hidden character ‬ : 62199‬
row 5164302 : hidden character ‬ : 62199‬
row 5164303 : hidden character ‬ : 62199‬
row 5164304 : hidden character ‬ : 62199‬
row 5164305 : hidden character ‬ : 62199‬
row 5164306 : hidden character ‬ : 62199‬
row 5164307 : hidden character ‬ : 62199‬
row 5164308 : hidden character ‬ : 62199‬
row 5164309 : hidden character ‬ : 62199‬
row 5164310 : hidden character ‬ : 62199‬
row 5164311 : hidden character ‬ : 62199‬
row 5164312 : hidden character ‬ : 62199‬
row 5164313 : hidden character ‬ : 62199‬
row 5164314 : hidden character ‬ : 62199‬
row 5164315 : hidden character ‬ : 62199‬
row 5164316 : hidden character ‬ : 62199‬
row 5164317 : hidden character ‬ : 62199‬
row 5164318 : hidden character ‬ : 62199‬
row 5164319 : hidden character ‬ : 62199‬
row 5164320 : hidden character ‬ : 62199‬
row 5164321 : hidden character ‬ : 62199‬
row 5164322 : hidden character ‬ : 62199‬
row 5164323 : hidden character ‬ : 62199‬
row 5164324 : hidden character ‬ : 62199‬
row 5164325 : hidden character ‬ : 62199‬
row 5164326 : hidden character ‬ : 62199‬
row 5164327 : hidden character ‬ : 62199‬
row 5164328 : hidden character ‬ : 62199‬
row 5164329 : hidden character ‬ : 62199‬
row 5164330 : hidden character ‬ : 62199‬
row 5164331 : hidden character ‬ : 62199‬
row 5164332 : hidden character ‬ : 62199‬
row 5164333 : hidden character ‬ : 62199‬
row 5164334 : hidden character ‬ : 62199‬
row 5164335 : hidden character ‬ : 62199‬
row 5164336 : hidden character ‬ : 62199‬
row 5164337 : hidden character ‬ : 62199‬
row 5164338 : hidden character ‬ : 62199‬
row 5164339 : hidden character ‬ : 62199‬
row 5164340 : hidden character ‬ : 62199‬
row 5164341 : hidden character ‬ : 62199‬
row 5164342 : hidden character ‬ : 62199‬
row 5164343 : hidden character ‬ : 62199‬
row 5164344 : hidden character ‬ : 62199‬
row 5164345 : hidden character ‬ : 62199‬
row 5164346 : hidden character ‬ : 62199‬
row 5164347 : hidden character ‬ : 62199‬
row 5164348 : hidden character ‬ : 62199‬
row 5164349 : hidden character ‬ : 62199‬
row 5164350 : hidden character ‬ : 62199‬
row 5164351 : hidden character ‬ : 62199‬
row 5164352 : hidden character ‬ : 62199‬
row 5164353 : hidden character ‬ : 62199‬
row 5164354 : hidden character ‬ : 62199‬
row 5164355 : hidden character ‬ : 62199‬
row 5164356 : hidden character ‬ : 62199‬
row 5164357 : hidden character ‬ : 62199‬
row 5164358 : hidden character ‬ : 62199‬
row 5164359 : hidden character ‬ : 62199‬
row 5164360 : hidden character ‬ : 62199‬
row 5164361 : hidden character ‬ : 62199‬
row 5164362 : hidden character ‬ : 62199‬
row 5164363 : hidden character ‬ : 62199‬
row 5164364 : hidden character ‬ : 62199‬
row 5164365 : hidden character ‬ : 62199‬
row 5164366 : hidden character ‬ : 62199‬
row 5164367 : hidden character ‬ : 62199‬
row 5164368 : hidden character ‬ : 62199‬
row 5164369 : hidden character ‬ : 62199‬
row 5164370 : hidden character ‬ : 62199‬
row 5164371 : hidden character ‬ : 62199‬
row 5164372 : hidden character ‬ : 62199‬
row 5164373 : hidden character ‬ : 62199‬
row 5164374 : hidden character ‬ : 62199‬
row 5164375 : hidden character ‬ : 62199‬
row 5164376 : hidden character ‬ : 62199‬
row 5164377 : hidden character ‬ : 62199‬
row 5164378 : hidden character ‬ : 62199‬
row 5164379 : hidden character ‬ : 62199‬
row 5164380 : hidden character ‬ : 62199‬
row 5164381 : hidden character ‬ : 62199‬
row 5164382 : hidden character ‬ : 62199‬
row 5164383 : hidden character ‬ : 62199‬
row 5164384 : hidden character ‬ : 62199‬
row 5164385 : hidden character ‬ : 62199‬
row 5164386 : hidden character ‬ : 62199‬
row 5164387 : hidden character ‬ : 62199‬
row 5164388 : hidden character ‬ : 62199‬
row 5164389 : hidden character ‬ : 62199‬
row 5164390 : hidden character ‬ : 62199‬
row 5164391 : hidden character ‬ : 62199‬
row 5164392 : hidden character ‬ : 62199‬
row 5164393 : hidden character ‬ : 62199‬
row 5164394 : hidden character ‬ : 62199‬
row 5164395 : hidden character ‬ : 62199‬
row 5164396 : hidden character ‬ : 62199‬
row 5164397 : hidden character ‬ : 62199‬
row 5164398 : hidden character ‬ : 62199‬
row 5164399 : hidden character ‬ : 62199‬
row 5164400 : hidden character ‬ : 62199‬
row 5164401 : hidden character ‬ : 62199‬
row 5164402 : hidden character ‬ : 62199‬
row 5164403 : hidden character ‬ : 62199‬
row 5164404 : hidden character ‬ : 62199‬
row 5164405 : hidden character ‬ : 62199‬
row 5164406 : hidden character ‬ : 62199‬
row 5164407 : hidden character ‬ : 62199‬
row 5164408 : hidden character ‬ : 62199‬
row 5164409 : hidden character ‬ : 62199‬
row 5164410 : hidden character ‬ : 62199‬
row 5164411 : hidden character ‬ : 62199‬
row 5164412 : hidden character ‬ : 62199‬
row 5164413 : hidden character ‬ : 62199‬
row 5164414 : hidden character ‬ : 62199‬
row 5164415 : hidden character ‬ : 62199‬
row 5164416 : hidden character ‬ : 62199‬
row 5164417 : hidden character ‬ : 62199‬
row 5164418 : hidden character ‬ : 62199‬
row 5164419 : hidden character ‬ : 62199‬
row 5164420 : hidden character ‬ : 62199‬
row 5164421 : hidden character ‬ : 62199‬
row 5164422 : hidden character ‬ : 62199‬
row 5164423 : hidden character ‬ : 62199‬
row 5164424 : hidden character ‬ : 62199‬
row 5164425 : hidden character ‬ : 62199‬
row 5164426 : hidden character ‬ : 62199‬
row 5164427 : hidden character ‬ : 62199‬
row 5164428 : hidden character ‬ : 62199‬
row 5164429 : hidden character ‬ : 62199‬
row 5164430 : hidden character ‬ : 62199‬
row 5164431 : hidden character ‬ : 62199‬
row 5164432 : hidden character ‬ : 62199‬
row 5164433 : hidden character ‬ : 62199‬
row 5164434 : hidden character ‬ : 62199‬
row 5164435 : hidden character ‬ : 62199‬
row 5164436 : hidden character ‬ : 62199‬
row 5164437 : hidden character ‬ : 62199‬
row 5164438 : hidden character ‬ : 62199‬
row 5164439 : hidden character ‬ : 62199‬
row 5164440 : hidden character ‬ : 62199‬
row 5164441 : hidden character ‬ : 62199‬
row 5164442 : hidden character ‬ : 62199‬
row 5164443 : hidden character ‬ : 62199‬
row 5164444 : hidden character ‬ : 62199‬
row 5164445 : hidden character ‬ : 62199‬
row 5164446 : hidden character ‬ : 62199‬
row 5164447 : hidden character ‬ : 62199‬
row 5164448 : hidden character ‬ : 62199‬
row 5164449 : hidden character ‬ : 62199‬
row 5164450 : hidden character ‬ : 62199‬
row 5164451 : hidden character ‬ : 62199‬
row 5164452 : hidden character ‬ : 62199‬
row 5164453 : hidden character ‬ : 62199‬
row 5164454 : hidden character ‬ : 62199‬

In [13]:
import re 

def remove_hidden_chars(text):
        if pd.isna(text):
              return text
        # Remove any character outside the printable ASCII range
        return re.sub(r'[^\x20-\x7E]', '', str(text))

# Apply the cleaning to the entire column
df['Serial Number'] = df['Serial Number'].apply(remove_hidden_chars)

# Verify if hidden characters still exist
for index, val in df['Serial Number'].items():
    valStr = str(val) 
    for c in str(valStr):
        if ord(c) > 127:
            print(f"row {index} : hidden character {c} : {valStr}")

In [17]:
df.to_csv('SCRAPED_MERGED_DATA_PROCESSED.csv', index=False)

In [14]:
filtered = df[df['FLIGHT TIME(mins)'] ==1726.0]
filtered1 = df[df['Serial Number'] ==1726]

# sort the values by the column 'FLIGHT TIME(mins)' desc 
df.sort_values(by='FLIGHT TIME(mins)', ascending=False, inplace=True)

In [15]:
df

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age(years),DATE,FROM,TO,FLIGHT,FLIGHT TIME(mins),STD,ATD,STA,STATUS,Color Code,ATA
4556572,ey-etd,a6-xwa,Etihad Airways,A35K,896596,315,5.0,30 Dec 2024,Chicago(ORD),Abu Dhabi(AUH),EY10,1732.0,13:10:00,13:31:00,12:20:00,Landed 04:23,red,04:23:00
10069676,ua-ual,n45440,United Airlines,B739,A583F5,33535.0,15.0,10 May 2024,Kansas City(MCI),Denver(DEN),UA1285,1439.0,09:16:00,09:40:00,10:13:00,Landed 08:38,green,08:38:00
10411549,ua-ual,n730yx,Republic Airways,E75L,A9CD47,17000518.0,9.0,03 May 2024,Louisville(SDF),Chicago(ORD),UA3650,1439.0,09:00:00,09:17:00,09:34:00,Landed 08:16,green,08:16:00
9691567,tk-thy,tc-jvz,Turkish Airlines,B738,4BAADA,60025.0,8.0,02 Jul 2024,Istanbul(IST),Sivas(VAS),TK2658,1439.0,08:25:00,08:56:00,10:00:00,Landed 8:56 AM,green,08:56:00
5364031,hu-chh,b-5625,Hainan Airlines,B738,780816,38146,13.0,08 Dec 2024,Lanzhou(LHW),Nanjing(NKG),HU7853,1439.0,13:30:00,15:47:00,15:55:00,Landed 3:47 PM,green,15:47:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11843583,SQ-SIA,9V-SCZ,Singapore Airlines,B78X,76CC7A,64805.0,0.0,09 Nov 2024,Adelaide (ADL),—,SQ279,NaN,08:41:00,NaN,NaN,Unknown,gray,NaN
11843670,SQ-SIA,9V-SCZ,Singapore Airlines,B78X,76CC7A,64805.0,0.0,12 Oct 2024,Singapore (SIN),Nagoya (NGO),SQ672,NaN,07:14:00,NaN,NaN,Unknown,gray,NaN
11843768,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,21 Jan 2025,Denpasar (DPS),Singapore (SIN),SQ937,NaN,12:05:00,12:16:00,14:55:00,Estimated 2:24 PM,green,NaN
11844000,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,12 Nov 2024,Singapore (SIN),Nagoya (NGO),SQ672,NaN,07:29:00,NaN,NaN,Unknown,gray,NaN
11844141,SQ-SIA,9V-SDA,Singapore Airlines,B78X,76CC81,67157.0,0.0,04 Oct 2024,Singapore (SIN),Mumbai (BOM),SQ422,NaN,12:31:00,NaN,NaN,Unknown,gray,NaN

In [11]:
filtered

Empty DataFrame
Columns: [Airline Code, Aircraft Registration, Operator, Type Code, Mode S, Serial Number, Age(years), DATE, FROM, TO, FLIGHT, FLIGHT TIME(mins), STD, ATD, STA, STATUS, Color Code, ATA]
Index: []

In [13]:
filtered1

,Airline Code,Aircraft Registration,Operator,Type Code,Mode S,Serial Number,Age(years),DATE,FROM,TO,FLIGHT,FLIGHT TIME(mins),STD,ATD,STA,STATUS,Color Code,ATA
1458789,ac-aca,c-gjvx,Air Canada,A321,C05EA6,1726.0,22.0,10 Dec 2024,Toronto(YYZ),Melbourne(MLB),AC2346,147.0,09:00:00,09:20:00,11:45:00,Landed 11:46 AM,green,11:46:00
1458790,ac-aca,c-gjvx,Air Canada,A321,C05EA6,1726.0,22.0,10 Dec 2024,Edmonton(YEG),Toronto(YYZ),AC176,194.0,00:05:00,01:01:00,06:00:00,Landed 6:15 AM,green,06:15:00
1458791,ac-aca,c-gjvx,Air Canada,A321,C05EA6,1726.0,22.0,09 Dec 2024,Toronto(YYZ),Edmonton(YEG),AC177,226.0,20:45:00,21:38:00,23:07:00,Landed 11:24 PM,yellow,23:24:00
1458792,ac-aca,c-gjvx,Air Canada,A321,C05EA6,1726.0,22.0,09 Dec 2024,Vancouver(YVR),Toronto(YYZ),AC108,244.0,11:25:00,11:54:00,18:57:00,Landed 6:58 PM,green,18:58:00
1458793,ac-aca,c-gjvx,Air Canada,A321,C05EA6,1726.0,22.0,09 Dec 2024,Toronto(YYZ),Vancouver(YVR),AC189,274.0,07:50:00,08:25:00,10:05:00,Landed 9:59 AM,green,09:59:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9146905,sv-sva,hz-aq12,Saudia,A333,7100B6,1726,8.0,17 Jan 2024,Riyadh(RUH),Dubai(DXB),SV584,96.0,22:15:00,22:29:00,01:10:00,Landed 01:05,green,01:05:00
9146906,sv-sva,hz-aq12,Saudia,A333,7100B6,1726,8.0,17 Jan 2024,Abha(AHB),Riyadh(RUH),SV1676,74.0,18:45:00,19:17:00,20:35:00,Landed 20:31,green,20:31:00
9146907,sv-sva,hz-aq12,Saudia,A333,7100B6,1726,8.0,17 Jan 2024,Riyadh(RUH),Abha(AHB),SV1675,94.0,16:05:00,16:20:00,17:55:00,Landed 17:55,green,17:55:00
9146908,sv-sva,hz-aq12,Saudia,A333,7100B6,1726,8.0,17 Jan 2024,Jeddah(JED),Riyadh(RUH),SV1032,70.0,13:00:00,13:33:00,14:45:00,Landed 14:43,green,14:43:00
9146909,sv-sva,hz-aq12,Saudia,A333,7100B6,1726,8.0,17 Jan 2024,Riyadh(RUH),Jeddah(JED),SV1027,96.0,10:00:00,10:20:00,11:55:00,Landed 11:56,green,11:56:00